### PR TITLE
Pivot io layers

### PR DESCRIPTION
**Pull request by falOn-Dev**

### CODE REVIEW

**Review by Something-Inconspicuous — APPROVED** [review]
I would *prefer* if the methods in `PivotIO` had kdocs, but I *guess* it's approvable without them. Also I already fixed the input field names :3

**Comment by falOn-Dev** [comment]
nah I'll add in those docs, stop adding @JvmField please it's unimportant, we should never be interacting with these outside of kotlin, so it's extra code to confuse people

**Review by mteam88 — APPROVED** [review]
lgtm

**Review by Something-Inconspicuous — CHANGES_REQUESTED** [review]
Actually, I have to ask you to change the `setP(p)` usages in `PivotIONeos#setPID` to use kotlin properties (`pidController.p = p`). Same thing goes with i and d, and double-check any time you use a get or set method if properties can be used.

ALSO also, your `PivotIO` implementations do not implement `setFF()`. Even if they don't support the operation, they should indicate that instead of doing nothing. I would recommend `UnsupportedOperationException`, but any kind of runtime indication would be sufficient. Or remove it, but that would be stupid in my opinion.

**Comment by falOn-Dev** [comment]
> Actually, I have to ask you to change the `setP(p)` usages in `PivotIONeos#setPID` to use kotlin properties (`pidController.p = p`). Same thing goes with i and d, and double-check any time you use a get or set method if properties can be used.
> 
> ALSO also, your `PivotIO` implementations do not implement `setFF()`. Even if they don't support the operation, they should indicate that instead of doing nothing. I would recommend `UnsupportedOperationException`, but any kind of runtime indication would be sufficient. Or remove it, but that would be stupid in my opinion.

Oops, missed those properties, on the topic of setFF the only thing that's actually useful for is if we did krakens, those can have their FF changed at any time, but we're not using them, I've been considering deleting them (or making a new ArmFeedforward that can change its gains)

**Pull request merged**
