### PR TITLE
Unit Library Helpers

### PR DESCRIPTION
**Pull request by Something-Inconspicuous**
Various helper extensions and functions to reduce verbosity in the wpilib units library. Please use it guys. You don't have to use raw doubles anymore. Please.

### CODE REVIEW

**Review by falOn-Dev — APPROVED** [review]
Indubitably!

**Comment by hamster1147** [comment]
I'll have to come visit you guys in the pits to talk about all the stuff you've guys done.

The RoboBees have been using our home built units for a couple years now and this year we also fully converted to Units, though not WPI's version.

Here's a snippet of our 2024 Telemetry class:
image

**Comment by hamster1147** [comment]
Units are pretty amazing to use once you fully switch.

**Comment by falOn-Dev** [comment]
I'm not sure about for Matthew specifically, but the biggest reason I was so interested in the new WPI units was after seeing the RoboBees using their own

**Comment by hamster1147** [comment]
Honestly really cool to hear that. I told the other mentors about it.

I'm planning to visit the Severn competition because the other teams I helped this year are going. I'll be sure to stop by your pit.

**Pull request merged**
