### PR TITLE
67 bob pivot rewrite cleanup

### LINKED ISSUE #67: BoB Pivot Rewrite / Cleanup
Pivot needs toe be rewritten and/or cleaned up for Battle o' Baltimore, here are the important features

- Controlled using PID, Feedforward, and Motion Profiling, view [THIS EXAMPLE](https://github.com/REVrobotics/2024-REV-ION-FRC-Starter-Bot/blob/main/src/main/java/frc/robot/subsystems/ArmSubsystem.java) to see how it can be implemented without feedforward, but it needs feedforward
- Have command factories within the subsystem for smaller commands, minimize boilerplate
- Use measures in as many possible locations, with radians as the bast unit for things like feedforward and PID control
- Keep it simple, stupid

I trust your judgement in determining the best ways to implement these.

### PR DESCRIPTION
**Pull request by Something-Inconspicuous**
External interactions with the pivot subsystem can only be done with measures, and methods for getting commands to set position both absolutely and relatively have been added. If there are any more things you would like the pivot subsystem to be able to do from the outside please let me know.

### CODE REVIEW

**Review by falOn-Dev — CHANGES_REQUESTED** [review]
Code looks good. You need to clean up the comments, not taking responsibility for your own code promotes a bad mentality to new students, but the code itself looks good.

**Review by falOn-Dev — APPROVED** [review]
Looks good! Don't merge these until it's tested on the bot though please, you're welcome to come to the shop this friday from 6-8 if you want to do that.

**Review by falOn-Dev — CHANGES_REQUESTED** [review]
Oops, I gotta re-open this. I need you to change it to not have logic in periodic, that's generally bad practice as periodic isn't mutexed.

You can do it more like the way I did it in this branch a little while ago that I forgot about: [link](https://github.com/Team2537/2024Crescendo/tree/post-season-rewrite-default) or if you don't feel like it I can move you over to intake and I can do pivot, your choice

**Review by falOn-Dev — CHANGES_REQUESTED** [review]
You're still doing this with logic in periodic, I'd really reccomend looking into the branch I sent you to get a better idea how robot code should be structured according to modern WPILib standards (which we ignored in past years)

**Comment by Something-Inconspicuous** [comment]
> You're still doing this with logic in periodic, I'd really reccomend looking into the branch I sent you to get a better idea how robot code should be structured according to modern WPILib standards (which we ignored in past years)

Okay, I do not -- or never did -- understand exactly what it is we would like to accomplish with the trapezoid profiles. If we want to avoid periodic logic, these seem like a bust considering that the previous example you gave me did exactly that. Now, if we wanted constant updates to the feed forward and PID, that would require periodic logic.

The newest commit is just with the trapezoid code commented out, because I think there is something missing here for me.

**Comment by falOn-Dev** [comment]
Trapezoidal profiles are definitely a pain to implement with REV hardware, it's difficult for me to explain, I'm happy to give you a different task like working on intake or climb (since climb code def needs an update to be not awful)

**Pull request closed without merging**
